//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Room
    {
        public int ClassRoom_Id { get; set; }
        public string ClassRoomName { get; set; }
        public Nullable<int> Shift_Id { get; set; }
        public Nullable<int> Section_Id { get; set; }
        public Nullable<int> Room_Id { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Room Room { get; set; }
        public virtual Section Section { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
