//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Routine
    {
        public int Class_Routine_Id { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public string Class_Dueation { get; set; }
        public Nullable<int> Period_Number { get; set; }
        public Nullable<int> Room_Number { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<int> Section_Id { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
        public Nullable<int> Shift_Id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Section Section { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
