//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.Exam_Result = new HashSet<Exam_Result>();
            this.Exam_Routine = new HashSet<Exam_Routine>();
        }
    
        public int Exam_Id { get; set; }
        public string Exam_Type { get; set; }
        public string Exam_Shedule { get; set; }
        public string Exam_Discription { get; set; }
        public bool Active_Status { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public System.DateTime Star_tTime { get; set; }
        public System.DateTime End_Time { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<int> Shift_Id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Result> Exam_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Routine> Exam_Routine { get; set; }
    }
}
