//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gardian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gardian()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Gardian_Id { get; set; }
        public string Gardian_Name { get; set; }
        public string Phone_NO { get; set; }
        public string Email { get; set; }
        public string ImageUrl { get; set; }
        public string Relation_Of_Gardian { get; set; }
        public string Gardian_NID_No { get; set; }
        public string Present_Address { get; set; }
        public Nullable<int> Pre_Division_Id { get; set; }
        public Nullable<int> Pre_District_Id { get; set; }
        public Nullable<int> Pre_Police_Station_Id { get; set; }
        public Nullable<int> Pre_Post_Office_Id { get; set; }
        public Nullable<int> Pre_Country_Id { get; set; }
        public string Parmanent_Address { get; set; }
        public Nullable<int> Par_Division_Id { get; set; }
        public Nullable<int> Par_District_Id { get; set; }
        public Nullable<int> Par_Police_Station_Id { get; set; }
        public Nullable<int> Par_Post_Office_Id { get; set; }
        public Nullable<int> Par_Country_Id { get; set; }
        public string Alt_Gardian_Name { get; set; }
        public string Relation_Of_Alt_Gardian { get; set; }
        public string Alt_Gardian_Phone_No { get; set; }
        public string Alt_Gardian_Email { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual District District { get; set; }
        public virtual District District1 { get; set; }
        public virtual Division Division { get; set; }
        public virtual Division Division1 { get; set; }
        public virtual Police_Station Police_Station { get; set; }
        public virtual Post_Office Post_Office { get; set; }
        public virtual Police_Station Police_Station1 { get; set; }
        public virtual Post_Office Post_Office1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
