//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Staff_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Gender { get; set; }
        public string Relagion { get; set; }
        public string Phone_NO { get; set; }
        public string Email { get; set; }
        public string NID_No { get; set; }
        public string ImageUrl { get; set; }
        public string Fathers_Name { get; set; }
        public string Mothers_Name { get; set; }
        public string Present_Address { get; set; }
        public Nullable<int> Pre_Division_Id { get; set; }
        public Nullable<int> Pre_District_Id { get; set; }
        public Nullable<int> Pre_Police_Station_Id { get; set; }
        public Nullable<int> Pre_Post_Office_Id { get; set; }
        public Nullable<int> Pre_Country_Id { get; set; }
        public string Parmanent_Address { get; set; }
        public Nullable<int> Par_Division_Id { get; set; }
        public Nullable<int> Par_District_Id { get; set; }
        public Nullable<int> Par_Police_Station_Id { get; set; }
        public Nullable<int> Par_Post_Office_Id { get; set; }
        public Nullable<int> Par_Country_Id { get; set; }
        public System.DateTime Joing_Date { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<System.DateTime> Resign_Date { get; set; }
        public Nullable<int> Designation_Id { get; set; }
        public Nullable<int> Brunch_Id { get; set; }
    
        public virtual Brunch Brunch { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual District District { get; set; }
        public virtual District District1 { get; set; }
        public virtual Division Division { get; set; }
        public virtual Division Division1 { get; set; }
        public virtual Police_Station Police_Station { get; set; }
        public virtual Police_Station Police_Station1 { get; set; }
        public virtual Post_Office Post_Office { get; set; }
        public virtual Post_Office Post_Office1 { get; set; }
    }
}
